config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :chat_rooms
  get '/', to: redirect('/chat')
  get '/chat', to: 'chat_client#show'
  namespace :api do
    resources :messages, only: [:index, :create]
    resources :chat_rooms, only: [:show]
  end

  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat_room.rb
require 'rest-client'

class ChatRoom < ApplicationRecord
  has_one :user

  def new_message(message_attributes)
    message = Messages.create!(message_attributes)
    notify_observers(message)
  end

  def wake_up
    message = { reply_url: '', chat_stream_id: '', style: '' }
    http_message("#{location}/wake", message)
  end

  private

  def notify_observers(message)
    broadcast_message message
    notify_bot message
  end

  def notify_bot(message)
    url = location.to_s
    reply_url = ENV['RUBY_CHAT_BASE_URL']
    message_json = message.as_json.merge(reply_url: reply_url)
    Rails.logger.info "Sending message to #{url}\n\tMessage being sent: #{message_json}"
    http_message(url, message_json)
  end

  def http_message(url, message_json)
    begin
      RestClient.post url, message_json
      return true
    rescue RestClient::ExceptionWithResponse => restError
      puts "Error notifying bot at #{location}"
      p restError
      return false
    rescue Errno::ECONNREFUSED => connError
      puts "Error connecting to bot at #{location}"
      p connError
      return false
    end
  end

  def broadcast_message(message)
    chat_stream_id = message.chat_stream_id
    puts "broadcasting to chat_#{chat_stream_id}"
    ActionCable.server.broadcast("chat_#{chat_stream_id}", message.as_json.merge(action: 'newMessage'))
  end
end

app/models/messages.rb
class Messages < ApplicationRecord
	validates :body, presence: true, length: {minimum: 2, maximum: 1000}
	validates :sender, presence: true
  has_one :chat_room
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :chat_rooms, optional: true
end

app/controllers/api/chat_rooms_controller.rb
module Api
  class ChatRoomsController < ApplicationController
    skip_before_action :verify_authenticity_token
    before_action :set_chat_room, only: [:show]

    def show
      roomStatus = ChatRoomStatus.new(@chat_room, chat_stream_id)
      render json: roomStatus, serializer: ChatRoomStatusSerializer
    end

    private

    def set_chat_room
      @chat_room = ChatRoom.find(params[:id])
    end
  end
end

app/controllers/api/messages_controller.rb
module Api
  class MessagesController < ApplicationController
    before_action :set_messages, only: [:index]
    skip_before_action :verify_authenticity_token

    def index
      render json: @messages, each_serializer: MessagesSerializer
    end

    def create
      room = ChatRoom.first
      room.new_message(message_attributes)
      render json: { 'success' => 'message sent' }
    end

    private

    def set_messages
      if has_admin_password?
        @messages = Messages.all
      else
        @messages = Messages.where(updated_at: Time.now-2.week..Time.now, chat_stream_id: chat_stream_id)
      end
    end

    def message_params
      params.require(:data).permit(
        attributes: [:body, :style, :sender, :chat_stream_id]
        )
    end

    def message_attributes
      attributes = { 'sender' => 1, 'style' => 'user', 'chat_stream_id' => chat_stream_id }
      attributes = attributes.merge(message_params[:attributes] || {})
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def authenticate_as_admin
    return render :file => "public/404.html", :status => :unauthorized unless has_admin_password?
  end

  def has_admin_password?
    params[:password] == 'monknee'
  end

  def chat_stream_id
    session[:chat_stream_id] ||= SecureRandom.uuid
  end
end

app/controllers/chat_client_controller.rb
class ChatClientController < ApplicationController
  layout 'ng_inject'

  def show
    render 'chat_client/index.html.haml'
  end

end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
  before_action :set_chat_room, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_as_admin

  def index
    @chat_rooms = ChatRoom.all
  end

  def show
  end

  def new
    @chat_room = ChatRoom.new
  end

  def edit
  end

  def create
    @chat_room = ChatRoom.new(chat_room_params)

    respond_to do |format|
      if @chat_room.save
        format.html { redirect_to @chat_room, notice: 'Chat room was successfully created.' }
        format.json { render :show, status: :created, location: @chat_room }
      else
        format.html { render :new }
        format.json { render json: @chat_room.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @chat_room.update(chat_room_params)
        format.html { redirect_to @chat_room, notice: 'Chat room was successfully updated.' }
        format.json { render :show, status: :ok, location: @chat_room }
      else
        format.html { render :edit }
        format.json { render json: @chat_room.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @chat_room.destroy
    respond_to do |format|
      format.html { redirect_to chat_rooms_url, notice: 'Chat room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chat_room
      @chat_room = ChatRoom.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chat_room_params
      params.require(:chat_room).permit(:name, :location, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_as_admin

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_bots_helper.rb
module ChatBotsHelper
end

app/helpers/chat_client_helper.rb
module ChatClientHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chat_bots/_form.html.erb
<%= form_for(chat_bot) do |f| %>
  <% if chat_bot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(chat_bot.errors.count, "error") %> prohibited this chat_bot from being saved:</h2>

      <ul>
      <% chat_bot.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :location %>
    <%= f.text_field :location %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/chat_client/index.html.haml
%app-root

app/views/chat_rooms/_form.html.erb
<%= form_for(@chat_room) do |f| %>
  <% if @chat_room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(chat_room.errors.count, "error") %> prohibited this chat_room from being saved:</h2>

      <ul>
      <% chat_room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :location %>
    <%= f.text_field :location %>
  </div>

  <div class="field">
    <%= f.label :users_id %>
    <%= f.text_field :users_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/chat_rooms/edit.html.erb
<h1>Editing Chat Room</h1>

<%= render 'form', chat_rooms: @chat_room %>

<%= link_to 'Show', @chat_room %> |
<%= link_to 'Back', chat_rooms_path %>

app/views/chat_rooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Chat Rooms</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @chat_rooms.each do |chat_room| %>
      <tr>
        <td><%= chat_room.name %></td>
        <td><%= chat_room.location %></td>
        <td><%= link_to 'Show', chat_room %></td>
        <td><%= link_to 'Edit', edit_chat_room_path(chat_room) %></td>
        <td><%= link_to 'Destroy', chat_room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Chat Rooms', new_chat_room_path %>

app/views/chat_rooms/new.html.erb
<h1>New Chat Room</h1>

<%= render 'form', chat_room: @chat_room %>

<%= link_to 'Back', chat_rooms_path %>

app/views/chat_rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @chat_room.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @chat_room.location %>
</p>

<%= link_to 'Edit', edit_chat_room_path(@chat_room) %> |
<%= link_to 'Back', chat_rooms_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyChat</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/ng_inject.html.haml
%head
  %script{:src => "/assets/zone.js/dist/zone.js"}
  %script{:src => "/assets/reflect-metadata/Reflect.js"}
= yield
= javascript_include_tag "inline.bundle.js"
= javascript_include_tag "vendor.bundle.js"
= javascript_include_tag "main.bundle.js"
= stylesheet_link_tag "styles.bundle.css"

app/views/messages/create.html.erb
<h1>Messages#create</h1>
<p>Find me in app/views/messages/create.html.erb</p>

app/views/messages/index.html.erb
<h1>Messages#index</h1>
<p>Find me in app/views/messages/index.html.erb</p>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>